root = "."
testdata_dir = "testdata"
tmp_dir = "air"

[build]
args_bin = ["-conf=dev"]
bin = "air\\main.exe"
cmd = "go build -o ./air/main.exe fuux/cmd/server"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata","ui","browser","dist","build"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = "2s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
