env: dev

listen: 2210

database:
  host: api.kickey.net
  port: 5433
  user: sa
  password: 8f06216b7esz828826f4202e5a99e2b9
  database: fuux_dev

jwt:
  secret: ziSRI5WpyjnZhMb2XtjxwC1D6BPhkzufWqn7KNb7XJzhdpcnutcR2oakfGSglROl8

